//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManagment.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PersonManagment.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        internal static string IdShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("IdShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string IncorrectConnectionType {
            get {
                return ResourceManager.GetString("IncorrectConnectionType", resourceCulture);
            }
        }
        
        internal static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        internal static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        internal static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        internal static string PersonalNumberValidation {
            get {
                return ResourceManager.GetString("PersonalNumberValidation", resourceCulture);
            }
        }
        
        internal static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        internal static string PhoneNumberValidation {
            get {
                return ResourceManager.GetString("PhoneNumberValidation", resourceCulture);
            }
        }
        
        internal static string InvalidPhoneType {
            get {
                return ResourceManager.GetString("InvalidPhoneType", resourceCulture);
            }
        }
        
        internal static string ImageFileRequired {
            get {
                return ResourceManager.GetString("ImageFileRequired", resourceCulture);
            }
        }
        
        internal static string InvalidImageFileType {
            get {
                return ResourceManager.GetString("InvalidImageFileType", resourceCulture);
            }
        }
        
        internal static string ImageFileSizeExceeded {
            get {
                return ResourceManager.GetString("ImageFileSizeExceeded", resourceCulture);
            }
        }
    }
}
